version: "3"

services:
  backend_test:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: backend_test
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    networks:
      - backend_test

networks:
  backend_test:
    external: true