version: "3"

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: backend_users
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    networks:
      - backend_users

networks:
  backend:
    external: true