version: "3"

services:
  backend_test:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: backend_test
    command: uvicorn main:app --host 0.0.0.0 --port ${APP_PORT}
    ports:
      - ${EXTERNAL_PORT}:${APP_PORT}
    networks:
      - backend_test
    env_file:
      - ../.env

networks:
  backend_test:
    external: true