version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5430:${DB_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - 15432:${PGADMIN_PORT}
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  contingent:
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: contingent
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - ../app/.env
    volumes:
      - ../user_photo:/user_photo


volumes:
  postgres:
  pgadmin:
  contingent: