from .benefits import BenefitsDataSh
from .contact import ContactDataSh
from .educational import EducationalDataSh
from .history import HistoryDataSh
from .millitary import MilitaryDataSh
from .order import OrderDataSh
from .other import OtherDataSh
from .personal import PersonalDataSh
from .short import ShortCard
from .stipend import StipendDataSh
from .students_card import StudentsCardSh
